version: "3"

services:
  database:
    image: postgres
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Seoul
    env_file:
      - ./env/.env
    ports:
      - "5432:5432"
    networks:
      - soup

  redis:
    image: redis
    volumes:
      - ./data/redis:/data
    env_file:
      - ./env/.env
    ports:
      - "6379:6379"
    networks:
      - soup

  minio:
    image: minio/minio
    volumes:
      - ./data/minio:/bucket
    env_file:
      - ./env/.env
    command: server --address ":9000" --console-address ":9001" /bucket
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      - soup

  create-bucket:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add soup http://minio:9000 soup soup2022;
      /usr/bin/mc mb soup/bucket;
      exit 0;
      "
    networks:
      - soup

networks:
  soup:
    labels:
      - soup
