name: Testing

on: push

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 1. Node JS Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: 2. Install Dependences
        run: yarn install

      - name: 3. Testing
        run: |
          yarn test
          yarn test:e2e

      - name: 4. Nest JS Build
        run: yarn build

