name: Testing

on:
  push:
    branches-ignore:
      - main
      - develop

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 1. set up node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'yarn'

      - name: 2. install dependences
        run: yarn install

      - name: 3. testing
        run: |
          yarn test --passWithNoTests
          yarn test:e2e --passWithNoTests

      - name: 4. nest.js build
        run: yarn build
